version: '3.2'
services:
  hs:
    container_name: sermo
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./app:/app/app:Z
      - ./test:/app/test:Z
      - ./src:/app/src:Z
      - ./static:/app/static:Z
      - ./package.yaml:/app/package.yaml:Z
      - ./stack.yaml:/app/stack.yaml:Z
      - ./config.yaml:/app/config.yaml:Z
    ports:
      - 8080:8080

  psql:
    image: postgres:11
