name:                hs-auth-example
version:             0.1.0.0
github:              "nishirken/hs-auth-example"
license:             BSD3
author:              "Dmitry Skurikhin"
maintainer:          "dmitrii.sk@gmail.com"
copyright:           "2018 Dmitry Skurikhin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-auth-example#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- lucid
- wai-middleware-static
- text
- postgresql-simple
- mtl
- jwt
- time
- cookie

library:
  source-dirs: src

executables:
  hs-auth-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-auth-example

tests:
  hs-auth-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-auth-example
    - hspec
    - QuickCheck
